### PR TITLE
Remove dialogs slot from section

### PR DESCRIPTION
**Pull request by steirico**
# Changes

This merge request removes the dialogs slot from the top-level `section` tag. Instead, a `div` tag becomes the top-level element which contains the  previous top-level `section` as well as the dialogs slot.

# Motivation

[Kirby 3 - Pagetable](https://github.com/sylvainjule/kirby-pagetable) is based on `tbl-for-kirby`. As such, Pagetable fills in the dialogs slot. `tbl-for-kirby` adds lots of css which is taken into account within the `section`:
```html
<section class="tbl" data-version="1.0.9">
```
As mentioned and elaborated in  in https://github.com/steirico/kirby-plugin-custom-add-fields/issues/9 the tables in dialogs opened from a `pagetable` section get polluted.

### CODE REVIEW

**Comment by distantnative** [comment]
Hmmm. I see the problem. But wouldn’t the cleaner solution be to do `.tbl > table` as the CSS rule?

**Comment by steirico** [comment]
Might be - I'm a backend developer and have limited knowledge in CSS. Therefore, IMHO it's the easiest and clearest solution to completely separate these elements and have the table in its own section. 

I just gave a try to your idea. But as far I can see lots of CSS/SCSS rules would have to be rewritten.

**Comment by distantnative** [comment]
I haven’t tried your solution cause I’m only on my phone, but it looks like `<table>` is still a child of the `.tbl` section - so it wouldn’t change anything

**Comment by steirico** [comment]
> but it looks like \<table\> is still a child of the .tbl section

Sorry, my comment was not clear on that one. My intention is to separate all the `tbl-for-kirby` stuff from the dialogs slot so that `tbl-for-kirby`-related CSS doesn't effect the formatting of fields in dialogs:

```html
<template>
  <div>
    <section class="tbl" data-version="1.0.9">
        ......
    </section>
    <slot name="dialogs" />
  </div>
</template>

**Comment by distantnative** [comment]
Integrated it manually :) Thanks for the idea

**Comment by steirico** [comment]
Great! Thank you very much!

**Pull request closed without merging**
